"use client";
import Image from "next/image";
import Link from "next/link";
import { useState, useEffect, useRef } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, MapPin, Plus, Minus, Phone, Utensils, Sparkles } from "lucide-react";
import { BookingButton } from "./SiteShell";
import { experiences, restaurant, signatures } from "@/lib/content";

function Flower({ className = "" }: { className?: string }) {
  return <svg className={className} viewBox="0 0 100 100" fill="none" aria-hidden="true">{Array.from({ length: 8 }, (_, i) => <ellipse key={i} cx="50" cy="29" rx="10" ry="22" transform={`rotate(${i * 45} 50 50)`} stroke="currentColor" strokeWidth="1" />)}<circle cx="50" cy="50" r="8" stroke="currentColor" /></svg>;
}
function ExperiencePanel({ open, id, children }: { open: boolean; id: string; children: React.ReactNode }) {
  const panel = useRef<HTMLDivElement>(null);
  useEffect(() => { if (panel.current) panel.current.inert = !open; }, [open]);
  return <div ref={panel} id={id} className="experience-panel-shell" data-open={open} aria-hidden={!open}><div className="experience-panel-clip"><div className="experience-panel">{children}</div></div></div>;
}

export default function HomeContent() {
  const [experience, setExperience] = useState(0);
  return <main id="main">
    <section className="hero" aria-labelledby="hero-heading">
      <div className="hero-copy"><div className="eyebrow"><span className="little-line" /> CHENNAI PALACE · HOLDEN HILL</div><h1 id="hero-heading">A little Chennai.<br />A lot of <em>soul.</em><span className="heading-spark">✳</span></h1><p>From the first crisp dosa to the last sip of filter coffee.<br className="desktop-break" /> South Indian flavours. A warm Adelaide welcome.</p><div className="hero-actions"><Link className="button" href="/menu">Explore the menu <ArrowUpRight size={19} /></Link><BookingButton className="text-link" /></div><div className="hero-footnote"><span className="small-flower">✳</span><span>Good food. Good company.<br /><strong>Always a place at our table.</strong></span></div></div>
      <div className="hero-visual"><div className="hero-arch"><Image src="/images/dosa.webp" alt="Golden masala dosa with traditional South Indian accompaniments" fill unoptimized priority loading="eager" fetchPriority="high" sizes="(max-width: 760px) 100vw, 55vw" /><div className="hero-image-shade" /><div className="hero-image-caption"><span>THE TASTE OF HOME</span><p>Tradition, served beautifully.</p></div></div><div className="round-stamp"><span>SOUTH INDIAN</span><Flower /><span>AT HEART</span></div><div className="image-note"><span className="note-dot" /> A little spice. A lot of love.</div></div>
      <a className="hero-scroll" href="#story"><ArrowDown size={15} /><span>A TASTE OF WHAT’S TO COME</span></a>
    </section>
    <div className="flavour-ribbon" aria-label="Dosa, Chettinadu, Biryani, Filter coffee"><div>{[0,1].map(i => <span className="ribbon-set" key={i} aria-hidden={i===1 ? true : undefined}><span>SOUTH INDIAN SOUL</span><b>✳</b><span>CHETTINADU SPICE</span><b>✳</b><span>BIRYANI TO SHARE</span><b>✳</b><span>COFFEE & CONVERSATION</span><b>✳</b></span>)}</div></div>
    <section className="story section-pad" id="story"><div className="story-side reveal"><span className="eyebrow">OUR ROOTS. YOUR TABLE.</span><Flower className="story-flower" /><span className="side-caption">FROM CHENNAI,<br />WITH LOVE.</span></div><div className="story-copy reveal"><h2>Some flavours take you places.<br />Ours bring you <em>home.</em></h2><div className="story-text"><p>From the dosa griddle to the Chettinad kitchen, our food tells a story of South Indian warmth, rich traditions and the joy of gathering around a table.</p><p>Begin with crisp dosa, idli and vada. Share a Chicken Chettinadu or a fragrant goat biryani. At Chennai Palace, there’s always another flavour to discover — and a reason to stay a little longer.</p></div><Link className="text-link" href="/menu">Get to know our kitchen <ArrowUpRight size={18} /></Link></div></section>
    <section className="signatures section-pad" id="kitchen"><div className="section-heading reveal"><div><span className="eyebrow">A TASTE OF CHENNAI PALACE</span><h2>Come for a favourite.<br /><em>Find a new one.</em></h2></div><Link className="text-link" href="/menu">View the full menu <ArrowUpRight size={18} /></Link></div><div className="signature-grid">{signatures.map(item => <article className="signature-card reveal" key={item.number}><Link href={item.href} className="signature-image"><Image src={item.image} alt={item.alt} fill sizes="(max-width: 640px) 90vw, (max-width: 1000px) 45vw, 30vw" /><span className="image-number">{item.number}</span><span className="image-arrow"><ArrowUpRight size={24} /></span></Link><div className="signature-copy"><span className="eyebrow">{item.label}</span><h3>{item.title}</h3><p>{item.description}</p><Link className="text-link" href={item.href}>{item.link}<ArrowRight size={16} /></Link></div></article>)}</div></section>
    <section className="experience-section section-pad" id="experiences"><div className="experience-heading reveal"><span className="eyebrow">MORE THAN A MEAL</span><h2>Your people.<br />Your occasion.<br /><em>Our pleasure.</em></h2><p>An everyday dinner or a day to remember.<br />There’s a place for it at Chennai Palace.</p><Flower className="experience-flower" /></div><div className="experience-accordion reveal">{experiences.map((item,i) => <div className={`experience-item ${experience === i ? "active" : ""}`} key={item.label}><h3><button aria-expanded={experience === i} aria-controls={`experience-${i}`} onClick={() => setExperience(experience === i ? -1 : i)}><span className="experience-number">0{i+1}</span><span>{item.label}</span>{experience===i ? <Minus size={20} /> : <Plus size={20} />}</button></h3><ExperiencePanel id={`experience-${i}`} open={experience===i}><div className="experience-panel-image"><Image src={item.image} alt="South Indian dishes to enjoy with friends and family" fill sizes="(max-width: 760px) 90vw, 40vw" /></div><h4>{item.title}</h4><p>{item.description}</p>{i===3 ? <a className="text-link" href={restaurant.phoneHref}>{item.action}<ArrowUpRight size={17} /></a> : <BookingButton className="text-link" topic={item.title}>{item.action}</BookingButton>}</ExperiencePanel></div>)}</div></section>
    <section className="coffee-banner"><Image src="/images/coffee.webp" alt="The traditional pour of South Indian filter coffee" fill sizes="100vw" /><div className="coffee-overlay" /><div className="coffee-copy reveal"><span className="eyebrow">THE FINISHING TOUCH</span><h2>Good things<br />are worth<br /><em>lingering over.</em></h2><p>One last pour. One more story.<br />Make time for a South Indian filter coffee.</p><Link className="button button-light" href="/menu?category=desserts">Something sweet to finish <ArrowUpRight size={18} /></Link></div><span className="coffee-caption">SOUTH INDIAN FILTER COFFEE · $4.00</span></section>
    <section className="visit-section section-pad" id="visit"><div className="visit-copy reveal"><span className="eyebrow">A LITTLE CLOSER THAN CHENNAI</span><h2>Find us in<br /><em>Holden Hill.</em></h2><p>Follow the aroma. Bring your appetite.<br />We’ll take care of the rest.</p><a className="address-link" href={restaurant.maps} target="_blank" rel="noopener noreferrer"><MapPin size={21} /><span>{restaurant.address}<br />{restaurant.locality}</span><ArrowUpRight size={20} /></a><div className="visit-actions"><a className="button" href={restaurant.maps} target="_blank" rel="noopener noreferrer">Get directions <ArrowUpRight size={17} /></a><a className="text-link" href={restaurant.phoneHref}><Phone size={16} />{restaurant.phone}</a></div></div><div className="hours-card reveal"><div className="hours-title"><Utensils size={24} strokeWidth={1.3} /><span className="eyebrow">MAKE YOURSELF AT HOME</span></div><h3>Time for a good meal.</h3>{restaurant.hours.map(hour => <div className="hours-row" key={hour.day}><span>{hour.day}</span><strong>{hour.time.split(" / ").map((time,i) => <span key={time}>{i>0 && <br />}{time}</span>)}</strong></div>)}<p className="hours-note">Please call to confirm Tuesday and public holiday hours.</p><div className="hours-bottom"><Sparkles size={17} /><span>Dining in, taking away, or celebrating?<br /><strong>We’d love to hear from you.</strong></span></div></div></section>
  </main>;
}
